SELECT F.COMPETENCIA,
       F.CCUSTO_ID,
       SUM(F.VR_SERVICO) FAT_BRUTO,
       SUM(F.BASE_CALCULO) FAT_LIQUIDO,
       D.VALOR_DESPESAS,
       D.VALOR_PESSOAL,
       COUNT(*) QTD_ALUNO
FROM FATURAMENTO F,
     CENTRO_CUSTO CC,
     DESPESA D
WHERE CC.CCUSTO_ID = F.CCUSTO_ID
AND   D.CENTRO_CUSTO = CC.CENTRO_CUSTO
AND   D.COMPETENCIA = F.COMPETENCIA
GROUP BY F.COMPETENCIA,
         F.CCUSTO_ID,
         CC.DESCRICAO,
         D.VALOR_PESSOAL,
         D.VALOR_DESPESAS
ORDER BY F.COMPETENCIA