SELECT FR.COMPETENCIA,
C.DESCRICAO,
FR.FAT_BRUTO,
FR.FAT_LIQUIDO ,
FR.VALOR_DESPESAS,
FR.VALOR_PESSOAL,
FR.QTD_ALUNO,
FR.DESC_INCONDICIONAL ,
FR.VALOR_IMPOSTOS ,
FR.TICKET_BRUTO ,
FR.TICKET_LIQUIDO,
FR.MARGEM_OPERACIONAL,
T.ANO,
T.MES
FROM FATO_RESULTADO FR, DIM_CENTRO_CUSTO C, DIM_TEMPO T
WHERE C.CCUSTO_ID  = FR.CCUSTO_ID 
AND T.DATA = FR.COMPETENCIA
ORDER BY FR.COMPETENCIA, C.DESCRICAO